### Herbert Rafael Reyes Portillo
### Carnet: 23002116

# Laboratorio 3

### Parte 1: Numpy:

Para los ejercicios siguiente genere el código que considere
para resolver el problema que se le plantea.

1. ¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [2]:

import numpy as np

arreglo = np.zeros(1000, dtype=bool)
size = arreglo.size * arreglo.itemsize
print("El tamaño del array en bytes es:", size)

El tamaño del array en bytes es: 1000


2. Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.

In [3]:
arreglo = np.arange(100,0,-2)
print(arreglo[-10:])

[20 18 16 14 12 10  8  6  4  2]


3) Dado el array

2 4 5 6

0 3 7 4

8 8 5 2

1 5 6 1

Seleccione con una instrucción el subarray de elementos

0 3 7 4

Después, seleccione el subarray de elementos

2 5

8 5

In [23]:
matriz = np.array([[2, 4, 5, 6],
                   [0, 3, 7, 4],
                   [8, 8, 5, 2],
                   [1, 5, 6, 1]])

print(matriz[1,:])
print(matriz[0::2,0::2])

[0 3 7 4]
[[2 5]
 [8 5]]


4. Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9],
obtenga la media aritmética de la diferencia (a-b).

In [28]:
a = np.array([1, 4, 2, 7])
b = np.array([1, 3, 2, 9])

diferencia=a-b
media = np.mean(diferencia)
print(media)

-0.25
