### Herbert Rafael Reyes Portillo
### Carnet: 23002116

# Laboratorio 3

### Parte 1: Numpy:

Para los ejercicios siguiente genere el código que considere
para resolver el problema que se le plantea.

1. ¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [2]:

import numpy as np

arreglo = np.zeros(1000, dtype=bool)
size = arreglo.size * arreglo.itemsize
print("El tamaño del array en bytes es:", size)

El tamaño del array en bytes es: 1000


2. Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.

In [3]:
arreglo = np.arange(100,0,-2)
print(arreglo[-10:])

[20 18 16 14 12 10  8  6  4  2]


3) Dado el array

2 4 5 6

0 3 7 4

8 8 5 2

1 5 6 1

Seleccione con una instrucción el subarray de elementos

0 3 7 4

Después, seleccione el subarray de elementos

2 5

8 5

In [23]:
matriz = np.array([[2, 4, 5, 6],
                   [0, 3, 7, 4],
                   [8, 8, 5, 2],
                   [1, 5, 6, 1]])

print(matriz[1,:])
print(matriz[0::2,0::2])

[0 3 7 4]
[[2 5]
 [8 5]]


4. Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9],
obtenga la media aritmética de la diferencia (a-b).

In [28]:
a = np.array([1, 4, 2, 7])
b = np.array([1, 3, 2, 9])

diferencia=a-b
media = np.mean(diferencia)
print(media)

-0.25


5. Tengo valores de cordenadas (x, y) en las columnas del array
1.33 4.5
30.0 10.7
70.2 0.5

Agregue a este array las coordenadas (37.1, -3.6). Muestre en pantalla las dimensiones del nuevo array.

In [33]:
array_cord = np.array([[1.33, 4.5],
                   [30.0, 10.7],
                   [70.2, 0.5]])

array_cord = np.vstack([array_cord,np.array([37.1,-3.6])])

print(f"Las nuevas dimensiones son: {array_cord.shape}")

Las nuevas dimensiones son: (4, 2)


6. Copie el array del ejercicio anterior. Traspóngalo (.Agregue ahora dos nuevos pares de coordenadas: (10.8,3.0) y (35.8, 12.0).

In [41]:
copy = np.copy(array_cord)
copy_t= copy.T


nuevas =     np.array([[10.8, 3.0],
                       [35.8, 12.0]])

copy_t = np.hstack([copy_t,nuevas])

print(f"Las nuevas dimensiones son: {copy_t.shape}")

Las nuevas dimensiones son: (2, 6)


## Parte 2: Exploración y Minería de Datos:
Con el dataset nucleospoblacion.csv adjunto al laboratorio,
luego responda las siguientes preguntas usando pandas y
matplotlib.

In [44]:
import pandas as pd

df = pd.read_csv('./Files/NucleosPoblacion.csv', delimiter=',', header=0)
df

FID  OBJECTID                           Texto  Poblacion  CodMun  \
0      0         1                         Agüimes    29431.0   35002   
1      1         2                         Antigua    10458.0   35003   
2      2         3                        Arrecife    58156.0   35004   
3      3         4                          Arucas    36745.0   35006   
4      4         5                          Gáldar    24473.0   35009   
..   ...       ...                             ...        ...     ...   
847  847       848             Infante Juan Manuel    14192.0   30030   
848  848       849           Santa Maria de Gracia    13349.0   30030   
849  849       850                    Vista Alegre    15208.0   30030   
850  850       851  Poligono Sta M de Benquerencia    19177.0   45168   
851  851       852                            Grao    16367.0   12040   

                                      Municipio  CodProvin  \
0                                       Agüimes         35   
1                                       Antigua         35   
2                                      Arrecife         35   
3                                        Arucas         35   
4                                        Gáldar         35   
..                                          ...        ...   
847                                      Murcia         30   
848                                      Murcia         30   
849                                      Murcia         30   
850                                      Toledo         45   
851  Castellón de la Plana/Castelló de la Plana         12   

              Provincia          X          Y  
0            Las Palmas -15.446012  27.900542  
1            Las Palmas -14.013301  28.418966  
2            Las Palmas -13.551451  28.960649  
3            Las Palmas -15.521512  28.117496  
4            Las Palmas -15.654111  28.143873  
..                  ...        ...        ...  
847              Murcia  -1.124304  37.979033  
848              Murcia  -1.202069  37.984024  
849              Murcia  -1.130564  37.995715  
850              Toledo  -3.948364  39.866699  
851  Castelló/Castellón   0.012911  39.973568  

[852 rows x 10 columns]

1. ¿Cuántos Municipios tienen más de 100000 habitantes?.

In [48]:
Municipios=df.loc[df['Poblacion'] > 100000, 'Municipio'].count()

print(f"La cantidad de municipios con mas de 100000 es de: {Municipios}")

La cantidad de municipios con mas de 100000 es de: 62
